CHAR_LIMIT = 15
BLANK_SPACE_CHAR = ' '
VERSION = "v1.0.0"
GAME_NAME = "NOVA_ULTIMATE"
GAME_DISPLAY_NAME = "Nova Pro X Ultimate"
DEVELOPER = "Zimcim"

DEFAULT_SPEED_MS = 100
MIN_SPEED_MS = 10
MAX_SPEED_MS = 500

WINDOW_WIDTH = 900
WINDOW_HEIGHT = 700

OLED_PREVIEW_COLOR = "#00FF00"
OLED_BACKGROUND = "black"

BUTTON_COLOR_ACTIVE = ["#1f538d", "#14375e"]
BUTTON_COLOR_DEFAULT = ["#3a7ebf", "#1f538d"]

CONFIG_FILE = "nova_settings.ini"
ASCII_DIR = "ascii_arts"

DEFAULT_SERVER_URL = "http://127.0.0.1:61369"